name: Deploy on EC2

on: 
  push: 
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Show All files
      run: ls -al
    - name: Show All files
      uses: appleboy/ssh-action@v1
      with:
         host: ${{ secrets.EC2_HOST }}
         username: ${{ secrets.EC2_USERNAME }}
         key: ${{ secrets.EC2_SSH_KEY }}
         port: 22
         script: |
           whoami
           pwd
           ls -lrt
           mkdir amol
